rules:
- id: dependencies
  languages: ['generic']
  message: $1 $2 $3
  pattern-either:
    - pattern-regex: ([\w\-\_]+)\s*(==|[~><]=?)\s*['"]?(\d+[\.\d+]*)['"]?
    # - pattern-regex: ([\w\-\_]+) not in ["']?((\d+[\.\d+]*)(,\s+\d+[\.\d+]*)*)["']?
  severity: INFO