name: Semgrep

on:
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: '0 0 * * 0'

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Find PyPI dependencies
      run: |
        semgrep ci
        semgrep --config ./.github/semgrep/rule.yml --output ./.github/semgrep/scan_results.json --json
    - name: Detect vulnerable dependencies
      run: python3 ./.github/semgrep/find_vulnerabilities.py

