name: Semgrep

on:
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: '0 0 * * 0'

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - name: Find PyPi dependencies
    - uses: actions/checkout@v3
    - run: semgrep ci
    - run: semgrep --config ./.github/semgrep/rule.yml --output ./.github/semgrep/scan_results.json --json
    - name: Detect vulnerable dependencies
    - uses: jannekem/run-python-script-action@v1.2

